name: build
run-name: ${{ github.actor }} is building splatapult
on: [push]
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install System Packages
        uses: ConorMacBride/install-package@v1
        with:
          apt: libgl-dev libxcb-glx0-dev libglu1-mesa-dev libxxf86vm-dev libxrandr-dev
      - name: Install CMake
        uses: lukka/get-cmake@latest
      - name: Install Vcpkg Packages
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgJsonGlob: 'vcpkg.json'
      - name: Configure and Build
        uses: lukka/run-cmake@v10
        with:
          configurePreset: 'make-vcpkg'
          buildPreset: 'make-vcpkg-release'
      - name: Dump contents of build
        run: tree -I vcpkg